### ISSUE TITLE
Scheduling refreshes isn't working

### ISSUE THREAD

**Issue by amandapteodoro** [Airtable-Labs/msft-power-query-m-language#6]
Using this query, Power BI does not allow to schedule the refresh due to the dynamic data source. 

I don't know how to fix the query and allow scheduling, but I am aware that with the previous query it was possible. 

Can anyone help?

![PBI ERROR](https://user-images.githubusercontent.com/127902254/225421380-9291be45-2f63-4bbf-ace5-593335f341ff.png)

**Comment by marks** [comment]
Hi @amandapteodoro - Thank you for bringing this to our attention. When you have a moment, can you retry using the modified queries available at PR https://github.com/Airtable-Labs/msft-power-query-m-language/pull/7.

If you are pulling a full table into Power BI, [this link](https://raw.githubusercontent.com/Airtable-Labs/msft-power-query-m-language/efcd19ea5b141aa38b64650c652f26987d87c3e0/retrieve-all-records-from-table.m) goes directly to the updated query for a full table.

**Comment by marks** [comment]
Hi @amandapteodoro - quick update - we have gone ahead and done additional internal testing and feel confident this works with ad-hoc and scheduled refreshes on app.powerbi.com. Please let us know when you confirm the new query is working for you.

The support article will be updated in the next few days.

**Comment by amandapteodoro** [comment]
Hey @marks , I tested the query and it worked great! 
I am very happy and grateful for all the support!
Thank you very much.
