### ISSUE TITLE
Missing "link to" type columns

### ISSUE THREAD

**Issue by gerleim** [Airtable-Labs/msft-power-query-m-language#8]
I have an 1:N table structure, and when querying the parent table, I don't see child records.
I also don't see Last Modified By (user) column - while I do see the Last Modified (date) column.

**Comment by gerleim** [comment]
Ok, so I tested the API with Postman, and columns are missing from the API response.
It's not an issue with the M query here.

**Comment by gerleim** [comment]
My finding is that colums missing from the API response if there is no value in the sampled recods.
Even if later records have content for these columns, it won't appear / create new columns.
https://community.airtable.com/t5/development-apis/field-missing-in-api/td-p/126473

So after all, this M query will might leave out columns.

**Comment by d-lange** [comment]
Due to the Airtable API not returning a field for a given record if there is no value and PowerBi's nuance of using the 1st record returned to establish the fields, this is a known behavior of the current example. 

A recommendation is to create a View in Airtable and then sort and/or filter in a way that makes that first record have a value for all fields you want to integrate with PowerBI. We have a note on this in our support article, but I will make a note to update this with more context.

**Comment by Shmayt** [comment]
Hello, 
@d-lange  thank you for the support, is the problem solved yet ?
even do a specific view on Airtable, filtered or sorted, yet the powerbi takes another record based on the date created
I hope I explained my issue well

**Comment by kmanley22** [comment]
There is a solution here: https://community.airtable.com/t5/other-questions/not-all-table-columns-loaded-to-power-bi/td-p/27831

In the M query, replace the following: 

```
 #"Expanded Record Fields" = Table.ExpandRecordColumn(
     #"Reordered Columns", "_airtableRecordFields",
     Record.FieldNames(#"Reordered Columns"{0}[_airtableRecordFields]),
     Record.FieldNames(#"Reordered Columns"{0}[_airtableRecordFields]))
in
    #"Expanded Record Fields"
```

with this: 

```
#"Expanded Record Fields" = Table.ExpandRecordColumn(
   #"Reordered Columns", "_airtableRecordFields",
   List.Distinct(List.Combine(List.Transform(List.Transform(Table.ToRecords(#"Reordered Columns"),each Record.Field(_,"_airtableRecordFields")), each Record.FieldNames(_)))),
   List.Distinct(List.Combine(List.Transform(List.Transform(Table.ToRecords(#"Reordered Columns"),each Record.Field(_,"_airtableRecordFields")), each Record.FieldNames(_)))))
in
   #"Expanded Record Fields"
```

It worked for me. It pulls all columns, even if the first row contains no data.

**Comment by Shmaytalyst** [comment]
Thank you very much dear friend, much appreciated

**Comment by d-lange** [comment]
Thanks @gerleim for filing this issue and to @kmanley22 for referencing the example in the community. I've just filed a [PR](https://github.com/Airtable-Labs/msft-power-query-m-language/pull/9) to update the queries to support this update. We'd really appreciate it if you could test it out and if you come across any issues. Thank you!
